version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: whisparr_server_1
      APP_PORT: 6969
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/hotio/whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-"Europe/Warsaw"}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure

  mac:
    image: getumbrel/media-app-configurator:v1.3.0@sha256:67e75dd9f5a14402b7816119a8e20189bc2465484cea077909d164687e59742b
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      APP_ID: "dead-whisparr"
      APP_URL: "http://dead-whisparr_server_1:6969"
      TRANSMISSION_HOST: "transmission_server_1"
      TRANSMISSION_PORT: 9091
      ROOT_FOLDER: "/downloads/movies"
      # optional qBittorrent download client
      QBITTORRENT_INSTALLED: ${APP_WHISPARR_QBITTORRENT_INSTALLED:-"false"}
      QBITTORRENT_HOST: "qbittorrent_server_1"
      QBITTORRENT_PORT: 8080
      # optional SABnzbd download client
      SABNZBD_INSTALLED: ${APP_WHISPARR_SABNZBD_INSTALLED:-"false"}
      SABNZBD_HOST: "sabnzbd_web_1"
      SABNZBD_PORT: 8080
      SABNZBD_API_KEY: ${APP_WHISPARR_SABNZBD_API_KEY:-""}