version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dead-convertx_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/c4illin/convertx:v0.14.1
    container_name: convertx
    restart: on-failure
    environment: # Defaults are listed below. All are optional.
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() by default
      - HTTP_ALLOWED=true # setting this to true is unsafe, only set this to true locally
      - ALLOW_UNAUTHENTICATED=true # allows anyone to use the service without logging in, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=24 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/convertx:/app/data